# Generated by Django 6.0.5 on 2026-05-19 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('taux', models.FloatField()),
                ('type_taux', models.CharField(max_length=10)),
                ('duree', models.IntegerField()),
                ('valeur_actuelle', models.FloatField()),
                ('interets_totaux', models.FloatField()),
                ('date_calcul', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_envoye', models.BooleanField(default=False)),
            ],
        ),
    ]
